//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApteka.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHECKS()
        {
            this.SHOPPING_LIST = new HashSet<SHOPPING_LIST>();
        }
    
        public int ID_CH { get; set; }
        public Nullable<int> ID_W { get; set; }
        public Nullable<System.TimeSpan> TIME_SALE { get; set; }
        public Nullable<System.DateTime> DATE_SALE { get; set; }
    
        public virtual WORKERS WORKERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOPPING_LIST> SHOPPING_LIST { get; set; }
    }
}
