//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApteka.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICINE()
        {
            this.INVOICE_LIST = new HashSet<INVOICE_LIST>();
            this.SHOPPING_LIST = new HashSet<SHOPPING_LIST>();
        }
    
        public int ID_M { get; set; }
        public string NAME_MED { get; set; }
        public Nullable<int> ID_C { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ID_R { get; set; }
        public Nullable<int> ID_F { get; set; }
        public Nullable<System.DateTime> DATE_DELIVERY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual CATEGORIES CATEGORIES { get; set; }
        public virtual FABRICATOR FABRICATOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE_LIST> INVOICE_LIST { get; set; }
        public virtual RELEASE_FORM RELEASE_FORM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOPPING_LIST> SHOPPING_LIST { get; set; }
    }
}
