//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApteka.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOPPING_LIST
    {
        public int ID_SL { get; set; }
        public Nullable<int> ID_M { get; set; }
        public Nullable<int> COUNTS { get; set; }
        public Nullable<int> ID_CH { get; set; }
    
        public virtual CHECKS CHECKS { get; set; }
        public virtual MEDICINE MEDICINE { get; set; }
    }
}
