//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApteka.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKERS()
        {
            this.CHECKS = new HashSet<CHECKS>();
        }
    
        public int ID_W { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> DATE_BIRTHDAY { get; set; }
        public Nullable<System.DateTime> DATE_ACCEPTANCE { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string TELEPHONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKS> CHECKS { get; set; }
    }
}
